# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            perNalin
tagline:          'Tech Bits and Humor Bites'
description:      'Nalin Perera'
url:              http://pernalin.com
baseurl:          /

author:

  name:           'Nalin Perera'
  url:            https://twitter.com/pernalin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/pernalin
